### PR TITLE
Fix/implicit tagging

### LINKED ISSUE #13: Revise implicit tagging
* I think my logic was flawed here: https://github.com/a-sit-plus/kmp-crypto/blob/82dccc97817fed4cc1bc79e194bd86942cadf61b/datatypes/src/commonMain/kotlin/at/asitplus/crypto/datatypes/asn1/BERTags.kt#L65
Can't we implicitly tag CONSTRUCTED ASN.1 Objects too? 
* Do we want to have the the [tag override](https://github.com/a-sit-plus/kmp-crypto/tree/feature/bitstring//datatypes/src/commonMain/kotlin/at/asitplus/crypto/datatypes/asn1/Asn1Encodable.kt#L49) for all `Asn1Decodables`? and merge this extended functionality in the base interface? As we have it now, this implicit tagging only makes sense for primitives, but this is obviously related to the first bullet.

Thoughts, anyone?!

### PR DESCRIPTION
**Pull request by JesusMcCloud**
closes #13

### CODE REVIEW

**Comment by iaik-jheher** [comment]
please remove whitespace changes so we can review the actual PR diff

**Comment by JesusMcCloud** [comment]
@iaik-jheher three lines of whitespace? I fail to see the issue

File: indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/CryptoSignature.kt [hunk 1]
```diff
@@ -28,33 +28,33 @@ sealed interface CryptoSignature : Asn1Encodable<Asn1Element> {
...
 
 
+    /**
+     * Well-defined CryptoSignatures, which can also be encoded to raw bytes, in addition to the DER encoding
+     * specified in the X.509 profile.
+     * RSA Signatures and EC Signatures with a known curve fall into this category.
+     *
+     * **This is the opposite of a [NotRawByteEncodable] signature**
+     */
+    sealed interface RawByteEncodable : CryptoSignature {
```
Comment (iaik-jheher) [inline indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/CryptoSignature.kt:38]: this entire section appears to do nothing except change the indentation

Comment (iaik-jheher) [reply indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/CryptoSignature.kt:38]: (i did not review the rest of the PR)

File: indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt [hunk 2]
```diff
@@ -162,8 +220,22 @@ sealed class Asn1Element(
                 return derEncoded
             }
 
+            /**
+             * Convenience helper to easily construct implicitly tagged elements.
+             * Shorthand for `Tag(tagValue, constructed=false, tagClass=TagClass.CONTEXT_SPECIFIC)
+             */
+            fun ULong.toImplicitTag() =
```
Comment (iaik-jheher) [inline indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt:227]: Is this not duplicating the (more explicit, pun not intended) `long withClass CONTEXT_SPECIFIC`?

File: indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt [hunk 3]
```diff
@@ -196,7 +267,7 @@ sealed class Asn1Element(
 
         val isConstructed by lazy { encodedTag.first().toUByte().isConstructed() }
 
-        val isExplicitlyTagged by lazy { isConstructed && tagClass == TagClass.CONTEXT_SPECIFIC }
+        internal val isExplicitlyTagged by lazy { isConstructed && tagClass == TagClass.CONTEXT_SPECIFIC }
```
Comment (iaik-jheher) [inline indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt:270]: this feels like it should be a getter

File: indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt [hunk 4]
```diff
@@ -196,7 +267,7 @@ sealed class Asn1Element(
 
         val isConstructed by lazy { encodedTag.first().toUByte().isConstructed() }
```
Comment (iaik-jheher) [inline indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt:268]: this also feels like it should be a getter

File: indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt [hunk 5]
```diff
@@ -233,6 +304,50 @@ sealed class Asn1Element(
...
+         * creates a new Tag from this object, overriding the class. Useful for implicitTagging (see [Asn1Structure.withImplicitTag])
+         */
+        infix fun withClass(tagClass: TagClass) =
+            Tag(this.tagValue, tagClass = tagClass, constructed = this.isConstructed)
+
+        /**
+         * creates a new Tag from this object, negating the passed property. Useful for implicitTagging (see [Asn1Structure.withImplicitTag]).
+         * This is a NOOP for tag that don't have this bit set.
+         */
+        infix fun without(negated: TagProperty): Tag = when (negated) {
```
Comment (iaik-jheher) [inline indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt:318]: did i miss it, or is `with` missing?

File: indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt [hunk 6]
```diff
@@ -321,32 +475,36 @@ class Asn1Sequence internal constructor(children: List<Asn1Element>) :
...
-    tag: Tag, children: List<Asn1Element>
+    tag: Tag, children: List<Asn1Element>, sort: Boolean
 ) :
     Asn1Structure(tag, children) {
     /**
      * ASN.1 CONSTRUCTED with custom tag
      * @param children the elements to put into this sequence
      * @param tag the custom tag to use
      * @param tagClass the tag class to use for this custom tag. defaults to [TagClass.UNIVERSAL]
+     * @param sort whether to sort the passed childr nodes. defautls to false
```
Comment (iaik-jheher) [inline indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt:486]: spelling: child, defaults

**Review by iaik-jheher — CHANGES_REQUESTED** [review]

File: indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt [hunk 7]
```diff
@@ -127,6 +128,63 @@ sealed class Asn1Element(
         return result
     }
 
+
+    /**
+     * Creates a new implicitly tagged ASN.1 Element from this ASN.1 Element.
+     * NOTE: The [TagClass] of the provided [tag] will be used! If you want the result to have [TagClass.CONTEXT_SPECIFIC],
+     * also invoke `tag withClass TagClass.CONTEXT_SPECIFIC`!. If a CONSTRUCTED Tag is applied to an ASN.1 Primitive,
```
[the remark this answers is not in the document]
Comment (JesusMcCloud) [reply indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt:135]: the first point i get, the second one, not. there are exactly four legal states for those bits and no extension is possible

File: indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt [hunk 8]
```diff
@@ -127,6 +128,63 @@ sealed class Asn1Element(
...
+        }
+
+        is Asn1Primitive -> Asn1Primitive(tag without CONSTRUCTED, content)
+    }
+
+    /**
+     * Creates a new implicitly tagged ASN.1 Element from this ASN.1 Element.
+     * Sets the class of the resulting structure to [TagClass.CONTEXT_SPECIFIC]
+     */
+    inline infix fun withImplicitTag(tagValue: ULong) = when (this) {
```
[the remark this answers is not in the document]
Comment (JesusMcCloud) [reply indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt:155]: no, it should not, because this one uses a pre-set class and the other does not (and the Docs also specify that)

File: indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt (hunk 2 above)
Comment (JesusMcCloud) [reply indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt:227]: it is, but you will need this all over the place when dealing with X.509

File: indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt (hunk 7 above)
[the remark this answers is not in the document]
Comment (iaik-jheher) [reply indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt:135]: the second one is purely about making it less verbose (`tag withClass CONTEXT_SPECIFIC` instead of `tag withClass TagClass.CONTEXT_SPECIFIC`)

by doing
```kotlin
sealed interface TagClass {
  companion object {
    val CONTEXT_SPECIFIC = ::CONTEXT_SPECIFIC
  }
}
data object CONTEXT_SPECIFIC: TagClass
```

File: indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt (hunk 5 above)
Comment (JesusMcCloud) [reply indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt:318]: why would you invite the creation of illegal ASN.1 structures that don't parse?

File: indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt (hunk 2 above)
Comment (iaik-jheher) [reply indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt:227]: then maybe a `Asn1.Tag(ULong)` constructor?

File: indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt (hunk 5 above)
Comment (iaik-jheher) [reply indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt:318]: ah, right

should `Tagged(42)` maybe be `Constructed(tag = 42)`?

File: indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt (hunk 7 above)
[the remark this answers is not in the document]
Comment (JesusMcCloud) [reply indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt]: i think we should agree to disagree on this point. four values, no extensions ever possible, zero complexity in those values -> it's an enum

[the remark this answers is not in the document]
Comment (iaik-jheher) [reply indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt]: my example has no added complexity 🤷 it just makes the code more readable/less verbose, same argument as something like `ULong.asImplicitTag` over `ULong withClass CONTEXT_SPECIFIC`

[the remark this answers is not in the document]
Comment (JesusMcCloud) [reply indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt]: neither two classes with the same name or one class which should behave like an enum, but does not is not my definition of "no added complexity", when i could just use a static import to get the same result in my code (see my last commit)

File: indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt (hunk 2 above)
Comment (JesusMcCloud) [reply indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt:230]: that would cause more confusion: is it implicit? should I use that when invoking Asn1Tagged? etc…

I do get that both structures and primitives may be tagged implicitly.
Still, this will be used and the function name combined with the API docs leaves little to be desired.
Build some X.509 structures. implicitly tagged primitives are just so common, that this shorthand is warranted.

Comment (iaik-jheher) [reply indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt:230]: `Asn1.ImplicitTag(ULong, tagClass = TagClass.CONTEXT_SPECIFIC)`?

Comment (iaik-jheher) [reply indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt:230]: (i'm especially concerned about polluting the IDE auto-complete with "toImplicitTag", where it is not immediately clear what context "implicit tag" is even referring to... and if you call it "toImplicitAsn1Tag" the constructor is the same length)

File: indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt (hunk 5 above)
Comment (JesusMcCloud) [reply indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt:321]: please provide a more comprehensive example, as I have a hard time wrapping my head around this suggestion (and maybe check [RFC 5280](https://datatracker.ietf.org/doc/html/rfc5280) and how your proposal aligns with the syntax and lingo there)

File: indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt (hunk 8 above)
[the remark this answers is not in the document]
Comment (JesusMcCloud) [reply indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt]: fixed. thanks!

File: indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt (hunk 2 above)
Comment (JesusMcCloud) [reply indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt]: > `Asn1.ImplicitTag(ULong, tagClass = TagClass.CONTEXT_SPECIFIC)`?
> 
> `42u.toImplicitTag()` is hardly shorter than `Asn1.ImplicitTag(42u)`

I like that! done (also for explicit tag)

File: indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt (hunk 5 above)
Comment (JesusMcCloud) [reply indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt:295]: done and ready for review

File: indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/pki/AlternativeNames.kt [hunk 9]
```diff
@@ -132,13 +131,13 @@ private constructor(private val extensions: List<Asn1Element>) {
...
-    val iPAddress = 7uL.toImplicitTag()
-    val registeredID = 8uL.toImplicitTag()
+    val otherName = Asn1.ImplicitTag(0uL)
+    val rfc822Name = Asn1.ImplicitTag(1uL)
+    val dNSName = Asn1.ImplicitTag(2uL)
+    val x400Address = Asn1.ImplicitTag(3uL)
+    val directoryName = Asn1.ImplicitTag(4uL)
+    val ediPartyName = Asn1.ImplicitTag(5uL)
+    val uniformResourceIdentifier = Asn1.ImplicitTag(6uL)
+    val iPAddress = Asn1.ImplicitTag(7uL)
```
Comment (iaik-jheher) [inline indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/pki/AlternativeNames.kt:141]: spelling: `ipAddress`

File: indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/pki/AlternativeNames.kt [hunk 10]
```diff
@@ -132,13 +131,13 @@ private constructor(private val extensions: List<Asn1Element>) {
...
-    val dNSName = 2uL.toImplicitTag()
-    val x400Address = 3uL.toImplicitTag()
-    val directoryName = 4uL.toImplicitTag()
-    val ediPartyName = 5uL.toImplicitTag()
-    val uniformResourceIdentifier = 6uL.toImplicitTag()
-    val iPAddress = 7uL.toImplicitTag()
-    val registeredID = 8uL.toImplicitTag()
+    val otherName = Asn1.ImplicitTag(0uL)
+    val rfc822Name = Asn1.ImplicitTag(1uL)
+    val dNSName = Asn1.ImplicitTag(2uL)
```
Comment (iaik-jheher) [inline indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/pki/AlternativeNames.kt:136]: spelling: `dnsName`

File: indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt (hunk 5 above)
Comment (iaik-jheher) [reply indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt:295]: should there be an `ExplicitlyTagged(tag: Asn1.Tag)` overload that checks if the tag is explicit?

Comment (JesusMcCloud) [reply indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt:295]: It would probably make more sense, to add `Structure(tag:Tag)`, letting you specify whatever you want, that returns a custom structure

Comment (JesusMcCloud) [reply indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt:295]: `Sequence{…} withImplicitTag` does that and does not get in your way with tag-altering checks

File: indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/pki/AlternativeNames.kt (hunk 10 above)
Comment (JesusMcCloud) [reply indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/pki/AlternativeNames.kt:136]: this is intentional: it uses the same off-casing as the RFC that specifies it

File: indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt (hunk 5 above)
Comment (JesusMcCloud) [reply indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt:295]: thing is, if you override anything but the numeric tag value, it is not an explicit tag any more, so it really does not make sense, because you'll end up with a custom structure

Comment (iaik-jheher) [reply indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt:295]: what if i want to take the (explicit) tag of some structure and create a new structure with the same (explicit) tag?

Comment (iaik-jheher) [reply indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt:295]: I'm thinking `fun ExplicitlyTagged(tag: Asn1.Tag, foo: ()->whatever) { require(tag.isExplicitTag); return ExplicitlyTagged(tag.tagValue, foo); }`

Comment (JesusMcCloud) [reply indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt:295]: > what if i want to take the (explicit) tag of some structure and create a new structure with the same (explicit) tag?

`Asn1.ExplicitTag(oldSctrucuter.tag.tagValue) {…}`

Again, the only variable for this DSL invocation is the numeric tag value, all other bits are fixed, so it makes no sense to allow passing other properties, just to cause confusion and invite user errors

**Comment by iaik-jheher** [comment]
resolve conflicts please

File: README.md [hunk 11]
```diff
@@ -432,72 +432,77 @@ DSL, which returns an `Asn1Structure`:
...
-        +Asn1.Bool(true)
-    }
-    +Asn1.Sequence {
-        +Asn1.Null()
-        +Asn1String.Numeric("12345")
-        +UtcTime(Clock.System.now())
-    }
-}
+  //fake Primitive
+  +(Asn1.Sequence { +Asn1.Int(42) } withImplicitTag (0x5EUL without CONSTRUCTED))
```
Comment (iaik-jheher) [inline README.md:460]: can we maybe use a pre-defined constructed tag (do we have this?) to give a more realistic example?

File: indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt [hunk 12]
```diff
@@ -181,6 +182,54 @@ sealed class Asn1Element(
...
+
+    /**
+     * Creates a new implicitly tagged ASN.1 Element from this ASN.1 Element.
+     * NOTE: The [TagClass] of the provided [tag] will be used! If you want the result to have [TagClass.CONTEXT_SPECIFIC],
+     * use `element withImplicitTag (tag withClass TagClass.CONTEXT_SPECIFIC)`!. If a CONSTRUCTED Tag is applied to an ASN.1 Primitive,
+     * the CONSTRUCTED bit is overridden and set to zero.
+     */
+    inline infix fun withImplicitTag(tag: Tag): Asn1Element = when (this) {
+        is Asn1Structure -> {
+            if (tag.isConstructed) Asn1CustomStructure(
```
Comment (iaik-jheher) [inline indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt:194]: indentation here is weird

File: indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt [hunk 13]
```diff
@@ -306,9 +398,16 @@ object Asn1EncodableSerializer : KSerializer<Asn1Element> {
...
+sealed class Asn1Structure(tag: Tag, children: List<Asn1Element>?, sort: Boolean = false) :
+    Asn1Element(TLV(tag, byteArrayOf()), if (!sort) children else children?.sortedBy { it.tag }) {
 
+    /**
+     * Whether this structure sorts child nodes or keeps them as-is.
+     * This **should** be true for SET and SET OF, but is set to false for SET and SET OF elements parsed
+     * from DER-encoded structures, because this has a chance of altering the structure for non-conforming DER-encoded
+     * structures.
+     */
+    val isSorted: Boolean = sort
```
Comment (iaik-jheher) [inline indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt:410]: why is this not in the constructor then

File: indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt [hunk 14]
```diff
@@ -306,9 +398,16 @@ object Asn1EncodableSerializer : KSerializer<Asn1Element> {
...
  */
-sealed class Asn1Structure(tag: Tag, children: List<Asn1Element>?) :
-    Asn1Element(TLV(tag, byteArrayOf()), children) {
+sealed class Asn1Structure(tag: Tag, children: List<Asn1Element>?, sort: Boolean = false) :
+    Asn1Element(TLV(tag, byteArrayOf()), if (!sort) children else children?.sortedBy { it.tag }) {
 
+    /**
+     * Whether this structure sorts child nodes or keeps them as-is.
+     * This **should** be true for SET and SET OF, but is set to false for SET and SET OF elements parsed
+     * from DER-encoded structures, because this has a chance of altering the structure for non-conforming DER-encoded
```
Comment (iaik-jheher) [inline indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt:407]: name & shame some examples 😈

File: indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Encodable.kt [hunk 15]
```diff
@@ -43,88 +43,90 @@ interface Asn1Encodable<A : Asn1Element> {
...
+        val expected = tagOverride ?: return
+        if (src.tag != expected)
+            throw Asn1TagMismatchException(expected, src.tag)
+    }
 
     /**
      * Exception-free version of [decodeFromTlv]
      */
-    fun decodeFromTlvOrNull(src: Asn1Primitive, tagOverride: Asn1Element.Tag?) =
+    fun decodeFromTlvOrNull(src: A, tagOverride: Asn1Element.Tag? = null) =
```
Comment (iaik-jheher) [inline indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Encodable.kt:104]: wasn't the plan to get rid of all of the tag override parameters? do we still need these?

**Review by iaik-jheher — CHANGES_REQUESTED** [review]

File: indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt (hunk 14 above)
Comment (JesusMcCloud) [reply indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt:407]: one comes to mind, but i am confident neither of us can even fathom how much garbage is out there. 

For the record: Apple is one offender that comes to mind

File: indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Encodable.kt (hunk 15 above)
Comment (JesusMcCloud) [reply indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Encodable.kt:104]: ??? you absolutely need this to decode while verifying implicit tags.

Comment (iaik-jheher) [reply indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Encodable.kt:104]: ah, it's not really a "tag override", it's more of an "asserted tag"? is this the right name?

File: indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt (hunk 14 above)
Comment (iaik-jheher) [reply indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt:407]: i meant give it as an example in the docs for why this is needed in practice, otherwise it's unintuitive why this would account for non-compliant code

File: indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt (hunk 13 above)
Comment (JesusMcCloud) [reply indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt:410]: good catch!

File: indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt (hunk 12 above)
Comment (JesusMcCloud) [reply indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt:194]: i fail to see it

File: indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt (hunk 14 above)
Comment (JesusMcCloud) [reply indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Elements.kt:413]: the comment already explains why this counter-intuitive flag is required. i am against pointing fingers in the docs here, because our implementation is also not feature-complete and allows for generating non-compliant structures, if we apply the SET tag to custom structures

File: indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Encodable.kt (hunk 15 above)
Comment (JesusMcCloud) [reply indispensable/src/commonMain/kotlin/at/asitplus/signum/indispensable/asn1/Asn1Encodable.kt]: you are right. it only checks if present. fixed!

File: README.md (hunk 11 above)
Comment (JesusMcCloud) [reply README.md:460]: A sequence has a predefined tag of 16 and has the constructed tag set. To me, this is a prime example of where how to implicitly tag and override the constructed bit

**Review by iaik-jheher — APPROVED** [review]
approved conditional on CI build
